package com.example.simplespringproject.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

/**
 * Represents a task in the system.
 * <p>
 * Each task has a description, a completion status, and is associated with a user.
 * </p>
 *
 * <p>
 * Annotations are used to specify the entity mappings and constraints.
 * </p>
 *
 * @see User
 */
@Getter
@Setter
@Entity
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "tasks")
public class Task {

    /**
     * The unique identifier for the task.
     * It is auto-generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The description of the task.
     * It must not be null or blank.
     */
    @NotNull
    @NotBlank
    private String description;

    /**
     * The completion status of the task.
     * It is false by default.
     */
    private boolean completed;

    /**
     * The user associated with the task.
     * This is a many-to-one relationship.
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * Constructs a new Task with the specified description and associated user.
     * The task is marked as not completed by default.
     *
     * @param description the description of the task
     * @param user the user associated with the task
     */
    public Task(String description, User user) {
        this.description = description;
        this.completed = false;
        this.user = user;
    }

}
