package com.example.todoapp.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.util.List;
/**
 * Represents a user in the system.
 * <p>
 * This entity is used for login and registration processes.
 * Each user has a unique username and a password.
 * Users can have multiple tasks associated with them.
 * </p>
 *
 * <p>
 * Annotations are used to specify the entity mappings and constraints.
 * </p>
 */
@Getter
@Setter
@Entity
@NoArgsConstructor
@Table(name = "users", uniqueConstraints = @UniqueConstraint(columnNames="username"))
public class User {
    /**
     * The unique identifier for the user.
     * It is auto-generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * The username of the user.
     * It must be unique and not null.
     */
    @NotNull
    private String username;
    /**
     * The password of the user.
     * It must not be null.
     */
    @NotNull
    private String password;

    /**
     * The list of tasks associated with the user.
     * This is a one-to-many relationship.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Task> tasks;

    /**
     * Constructs a new User with the specified username and password.
     *
     * @param username the username of the user
     * @param password the password of the user
     */
    public User(String username, String password){
        this.username = username;
        this.password = password;
    }
}
